# Generated by Django 4.0.6 on 2022-07-29 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 19, 6, 7, 440833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 19, 6, 7, 440833, tzinfo=utc)),
        ),
    ]
