# Generated by Django 4.1 on 2022-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_notification_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/msgpics'),
        ),
    ]
